#!/bin/bash
######################
# author : Nishanth
# date :22 Oct'25
# this script reports the AWS usage
######################

# AWS S3
# AWS EC2
# AWS IAM
# AWS lambda

#list S3 buckets
aws s3 ls
#list EC2-instances
aws ec2 decribe-instances
#list iam users
aws iam list-users
#list lambda funtions
aws lambda list-functions
